---
- name: Add doppler api-key
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ external_secrets.doppler.secret.name }}"
        namespace: "{{ external_secrets.namespace }}"
      data:
        dopplerToken: "{{ external_secrets_doppler_secret_token | b64encode }}"
