---
- name: Create projects
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: "{{ argocd.bootstrapProject.name }}"
        namespace: "{{ argocd.bootstrapProject.namespace }}"
      spec:
        clusterResourceWhitelist:
          - group: "{{ argocd.bootstrapProject.spec.clusterResourceWhitelist.group }}"
            kind: "{{ argocd.bootstrapProject.spec.clusterResourceWhitelist.kind }}"
        destinations:
          - namespace: "{{ argocd.bootstrapProject.spec.destinations.namespace }}"
            server: "{{ argocd.bootstrapProject.spec.destinations.server }}"
        sourceRepos:
          - "{{ argocd.bootstrapProject.spec.sourceRepo }}"

- name: Create bootstrap application
  kubernetes.core.k8s:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: argocd-bootstrap
        namespace: "{{ argocd.namespace }}"
      spec:
        destination:
          namespace: "{{ argocd.namespace }}"
          server: "https://kubernetes.default.svc"
        project: "{{ argocd.bootstrap.project }}"
        source:
          helm:
            valueFiles:
              - values.yaml
          path: .
          repoURL: "{{ argocd.bootstrap.url }}"
          targetRevision: "{{ argocd.bootstrap.revision | default('HEAD') }}"
        syncPolicy:
          automated:
            prune: "{{ argocd.bootstrap.sync_options.prune | default(true) }}"
            selfHeal: "{{ argocd.bootstrap.sync_options.selfHeal | default(true) }}"
  # TODO: currently we simply skip this in check mode since it can't be verified on first install (CRD isn't available)
  when: not ansible_check_mode