---
- name: Add doppler api-key
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ external_secrets.doppler.secret.name }}"
        namespace: "{{ external_secrets.namespace }}"
      data:
        dopplerToken: "{{ external_secrets_doppler_secret_token | b64encode }}"

- name: Add doppler SecretStore
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: "{{ external_secrets.secretStore.name }}"
        namespace: "{{ external_secrets.secretStore.namespace }}"
      spec:
        provider:
          doppler:
            auth:
              secretRef:
                dopplerToken:
                  name: "{{ external_secrets.doppler.secret.name }}"
                  key: "dopplerToken"
