---
- name: Install external-secrets operator
  kubernetes.core.helm:
    name: "{{ external_secrets.name }}"
    release_namespace: "{{ external_secrets.namespace }}"
    chart_ref: "{{ external_secrets.chart.ref }}"
    chart_version: "{{ external_secrets.chart.version }}"
    update_repo_cache: true
    atomic: true
    values: "{{ lookup('template', 'external_secrets.yaml.j2') | from_yaml }}"
